version: '2'

services:
  dev:
    container_name: "codeigniter-test"
    build: ./php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: igniter_test
      MYSQL_USER: root
      MYSQL_PASSWORD: 2123
      MYSQL_ROOT_PASSWORD: hoge
      TZ: "Asia/Tokyo"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
